services:
  - type: web
    name: iptv-php-api
    env: php
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    rootDir: .
    envVars:
      - key: APP_ENV
        value: production
