services:
  - type: web
    name: stalker-player
    env: php
    plan: free
    buildCommand: |
      chmod +x build-render.sh
      ./build-render.sh
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: RENDER
        value: true
      - key: PORT
        generateValue: true
